[book]
authors = ["Jaroslaw Konik"]
language = "en"
multilingual = false
src = "src"
title = "bevy_scriptum"

[preprocessor.keeper]
command = "mdbook-keeper"
manifest_dir = "."
externs = ["bevy", "bevy_scriptum"]
build_features = ["luajit", "rhai"]
